// AUTO-GENERATED by scripts/build-textures-ktx2.mjs — do not edit.
// Basenames whose .ktx2 counterpart exists and can be served to KTX2Loader.
export const KTX2_AVAILABLE: Set<string> = new Set([
  "callisto",
  "ceres",
  "charon",
  "earth-bump",
  "earth-clouds-alpha",
  "earth-clouds",
  "earth-night",
  "earth-specular",
  "earth",
  "eris",
  "europa",
  "haumea",
  "jupiter",
  "makemake",
  "mars-bump",
  "mars",
  "mercury-bump",
  "mercury",
  "moon-bump",
  "moon",
  "neptune",
  "pluto",
  "saturn",
  "sun",
  "triton",
  "uranus",
  "venus-bump",
  "venus",
]);
// Intentional JPG fallbacks: processed by the builder, but the KTX2 output
// was larger than the source, so the loader serves the JPG. Pruned from disk.
export const KTX2_JPG_FALLBACK: Set<string> = new Set([
  "ganymede",
  "io",
]);
